name: GitHub Actions
on: [push]
env:
  PROJECT: micro-services

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm ci
      - run: npm run build --if-present

      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}


    # job:
    # job_id:
      # steps:
      - id: 'auth'
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v0'

      - name: 'Use gcloud CLI'
        run: 'gcloud info'



      # - name: Setup GCP Service Account
      #   uses: google-github-actions/setup-gcloud@v0
      #   with:
      #     project_id: ${{env.PROJECT}}
      #     service_account_key: ${{ secrets.private_key }}
      #     export_default_credentials: true

      # - name: deploy cloud function
      #   id: deploy
      #   uses: google-github-actions/deploy-cloud-functions@main
      #   with:
      #     name: ILoveMkdev
      #     runtime: java11
      #     project_id: mkdevyoutube
      #     entry_point: functions.ILoveMkdev

      # - name: make the url aunthenticated
      #   run: |
      #     gcloud functions add-iam-policy-binding ILoveMkdev --member="allUsers" --role="roles/cloudfunctions.invoker"
      # - name: test the url
      #   run: curl "${{ steps.deploy.outputs.url }}"